2025-04-13 16:22:18,529 - ERROR - Internal Server Error: /update-initiatives/32
Traceback (most recent call last):
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py", line 516, in post
    initiative.save()
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\db\models\base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\db\models\base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\db\models\query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\db\models\sql\compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\db\models\fields\__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\db\models\fields\__init__.py", line 1536, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\db\models\fields\__init__.py", line 1531, in get_prep_value
    return self.to_python(value)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\db\models\fields\__init__.py", line 1497, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“” value has an invalid date format. It must be in YYYY-MM-DD format.']
2025-04-13 16:52:20,448 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\models.py changed, reloading.
2025-04-13 16:53:55,782 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\models.py changed, reloading.
2025-04-13 18:47:40,232 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\models.py changed, reloading.
2025-04-13 18:48:53,847 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-13 19:01:16,655 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-13 19:11:02,578 - WARNING - Not Found: /family-sponsors/
2025-04-25 18:48:26,705 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 19:37:10,490 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 19:41:23,403 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 19:42:45,018 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 19:47:00,877 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 19:56:39,835 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:01:36,699 - ERROR - Internal Server Error: /initiatives/
Traceback (most recent call last):
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py", line 211, in get_context_data
    origin_map = Map(location=[20, 0], zoom_start=2, tiles='Stamen Terrain')  # Start map centered at a global view
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\folium\folium.py", line 322, in __init__
    tile_layer = TileLayer(
                 ^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\folium\raster_layers.py", line 143, in __init__
    raise ValueError("Custom tiles must have an attribution.")
ValueError: Custom tiles must have an attribution.
2025-04-27 20:01:37,037 - WARNING - Not Found: /favicon.ico
2025-04-27 20:03:31,190 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:03:34,324 - ERROR - Internal Server Error: /initiatives/
Traceback (most recent call last):
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py", line 211, in get_context_data
    origin_map = Map(location=[20, 0], zoom_start=2, tiles='Stamen Terrain')  # Start map centered at a global view
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\folium\folium.py", line 322, in __init__
    tile_layer = TileLayer(
                 ^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\folium\raster_layers.py", line 143, in __init__
    raise ValueError("Custom tiles must have an attribution.")
ValueError: Custom tiles must have an attribution.
2025-04-27 20:03:53,463 - ERROR - Internal Server Error: /initiatives/
Traceback (most recent call last):
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py", line 211, in get_context_data
    origin_map = Map(location=[20, 0], zoom_start=2, tiles='Stamen Terrain')  # Start map centered at a global view
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\folium\folium.py", line 322, in __init__
    tile_layer = TileLayer(
                 ^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\folium\raster_layers.py", line 143, in __init__
    raise ValueError("Custom tiles must have an attribution.")
ValueError: Custom tiles must have an attribution.
2025-04-27 20:04:14,439 - ERROR - Internal Server Error: /initiatives/
Traceback (most recent call last):
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py", line 211, in get_context_data
    origin_map = Map(location=[20, 0], zoom_start=2, tiles='Stamen Terrain')  # Start map centered at a global view
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\folium\folium.py", line 322, in __init__
    tile_layer = TileLayer(
                 ^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\folium\raster_layers.py", line 143, in __init__
    raise ValueError("Custom tiles must have an attribution.")
ValueError: Custom tiles must have an attribution.
2025-04-27 20:06:27,175 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:06:31,082 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:06:35,882 - ERROR - Internal Server Error: /initiatives/
Traceback (most recent call last):
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py", line 215, in get_context_data
    folium.TileLayer('cartodb positron').add_to(origin_map)  # Adds a satellite-style view
    ^^^^^^
NameError: name 'folium' is not defined
2025-04-27 20:06:51,009 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:07:01,625 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:11:09,894 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:13:42,270 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:14:16,315 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:14:28,256 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:14:34,256 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:14:50,026 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:15:23,656 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:16:01,507 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:16:33,977 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:17:22,607 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:20:51,637 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:25:39,597 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:26:11,997 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:26:24,788 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:26:37,544 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:26:56,438 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:27:01,471 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:27:31,711 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-27 20:28:03,425 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 07:43:03,455 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 07:43:10,603 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 07:44:04,375 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 07:48:04,630 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 07:54:41,261 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 07:57:14,784 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 07:57:23,678 - ERROR - Internal Server Error: /initiatives/
Traceback (most recent call last):
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py", line 214, in get_context_data
    Marker(
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\folium\map.py", line 402, in __init__
    self.location = validate_location(location) if location is not None else None
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emine\OneDrive\Documents\tigray_repo\env\Lib\site-packages\folium\utilities.py", line 88, in validate_location
    raise ValueError(
ValueError: Expected two (lat, lon) values for location, instead got: [[-34.83333, 18.36667], [37.34999, -17.66667], [37.34999, 51.20833], [-34.83333, 51.20833]].
2025-04-28 07:57:24,415 - WARNING - Not Found: /favicon.ico
2025-04-28 07:57:31,528 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 07:57:45,277 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 07:59:13,506 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 08:00:56,737 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 08:01:57,677 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 08:05:31,392 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 08:06:07,475 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 08:07:18,083 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 09:10:17,157 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 09:10:59,330 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 09:12:42,153 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 09:13:47,613 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 09:14:04,800 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 09:14:22,141 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 09:45:21,688 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 09:46:16,016 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 09:59:12,606 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 09:59:39,795 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-28 19:37:49,317 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\tigray_data_repo\settings.py changed, reloading.
2025-04-29 07:01:17,252 - WARNING - Not Found: /favicon.ico
2025-04-29 07:17:09,579 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\models.py changed, reloading.
2025-04-29 07:17:31,072 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\models.py changed, reloading.
2025-04-29 13:41:52,477 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-29 13:42:25,871 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-04-29 13:43:40,277 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\models.py changed, reloading.
2025-04-29 13:52:18,047 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\models.py changed, reloading.
2025-04-29 13:52:27,715 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\models.py changed, reloading.
2025-05-18 17:26:01,526 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-05-18 17:28:43,170 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\models.py changed, reloading.
2025-05-18 17:29:38,640 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\models.py changed, reloading.
2025-05-18 17:29:47,576 - WARNING - Not Found: /favicon.ico
2025-05-18 17:30:12,568 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\models.py changed, reloading.
2025-05-18 17:40:47,317 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\models.py changed, reloading.
2025-05-18 17:51:41,291 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-05-18 17:52:12,416 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-05-18 17:52:39,677 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-05-18 18:44:06,865 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-05-18 18:49:47,308 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-06-07 23:16:56,438 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-06-07 23:17:47,990 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-06-07 23:18:18,255 - INFO - C:\Users\emine\OneDrive\Documents\tigray_repo\tigray_data_repo\App\views.py changed, reloading.
2025-07-14 17:36:45,948 - WARNING - Not Found: /favicon.ico
2025-07-14 17:39:34,223 - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-07-24 09:33:09,828 - WARNING - Not Found: /favicon.ico
